spring:
  application:
    name: HAUT Survivor
  datasource:
    url: jdbc:mysql://localhost:3306/haut_survivor?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080
